package co.daneshyarwithmahdikhorshidi.testbizcard

data class PortfolioList(
    val id:Int,
    val name:String,
    val familyName:String,
    val projectName:String
    )


fun portfolioList():List<PortfolioList>{
    return listOf(
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
        PortfolioList(id = 1, name = "Mahdi", familyName = "Khorshidi", projectName = "taminshid.com"),
    )
}
